/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // M3 Dark Scheme
        "primary": "#bec2ff",
        "on-primary": "#000ba6",
        "primary-container": "#7a85ff",
        "on-primary-container": "#000992",
        "primary-fixed": "#e0e0ff",
        "primary-fixed-dim": "#bec2ff",
        "inverse-primary": "#3d4ae0",
        "secondary": "#50d8e9",
        "on-secondary": "#00363c",
        "secondary-container": "#00b1c2",
        "on-secondary-container": "#003e44",
        "tertiary": "#ffb689",
        "on-tertiary": "#512300",
        "tertiary-container": "#e0731d",
        "on-tertiary-container": "#471e00",
        "surface": "#131314",
        "on-surface": "#e5e2e3",
        "surface-dim": "#131314",
        "surface-bright": "#3a393a",
        "surface-container-lowest": "#0e0e0f",
        "surface-container-low": "#1c1b1d",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "on-surface-variant": "#c6c5d8",
        "background": "#131314",
        "on-background": "#e5e2e3",
        "outline": "#8f8fa1",
        "outline-variant": "#454655",
        "inverse-surface": "#e5e2e3",
        "inverse-on-surface": "#313031",
        "surface-tint": "#bec2ff",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        // Brand Custom Extensions
        "custom-bg": "#070708",
        "custom-divider": "#232426",
        "custom-divider-light": "#1B1C1E",
        "custom-card-bg": "#101112",
        "custom-card-bg-alt": "#151617",
        "custom-sidebar": "#0d0e0f",
        "custom-panel": "#111214",
        "custom-text-muted": "#9A9DA3",
        "custom-btn-primary": "#5E6BFF",
        "custom-btn-text": "#F0F1F2",
        "brand-primary": "#5E6BFF",
        "brand-primary-hover": "#4a55cc",
        "brand-primary-text": "#F0F1F2",
        "brand-secondary-text": "#9A9DA3",
        "brand-border": "#1B1C1E",
        "brand-border-strong": "#232426",
        "signal-positive": "#50d8e9",
        "signal-warning": "#ffb689",
        "signal-accent": "#E5FD17",
        "signal-active": "#22c55e",
        "signal-critical": "#ef4444",
        "signal-brand": "#5E6BFF",
      },
      borderRadius: {
        DEFAULT: "12px",
        sm: "6px",
        lg: "12px",
        xl: "16px",
        full: "9999px",
        button: "12px",
        card: "12px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "20px",
        "margin-safe": "32px",
        "section-lg": "64px",
      },
      fontFamily: {
        h1: ["Manrope", "sans-serif"],
        h2: ["Manrope", "sans-serif"],
        h3: ["Manrope", "sans-serif"],
        h4: ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "monospace"],
      },
      fontSize: {
        "hero-headline": ["76px", { lineHeight: "1.1", letterSpacing: "-0.055em", fontWeight: "520" }],
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "520" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.05em", fontWeight: "520" }],
        h3: ["24px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "520" }],
        h4: ["18px", { lineHeight: "1.4", letterSpacing: "-0.02em", fontWeight: "520" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "mono-data": ["13px", { lineHeight: "1", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
